apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eqwv24jpq-python
  janus-idp.io/tekton: eqwv24jpq-python
  backstage.io/kubernetes-id: eqwv24jpq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eqwv24jpq-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
